// <auto-generated />
namespace StackUndertow_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class justtosee : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(justtosee));
        
        string IMigrationMetadata.Id
        {
            get { return "201702152221092_justtosee"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
